const enterpises = [
  {
    enterpriseName: "Bonvoy",
    logo: "/images/enterprises/logos/bonvoy.jpg",
  },
  {
    enterpriseName: "Marriot",
    logo: "/images/enterprises/logos/marriott.jpg",
  },
  {
    enterpriseName: "City Express",
    logo: "/images/enterprises/logos/city-express.jpg",
  },
];

const addresses = [
  {
    officeName: "City Express Junior Aguascalientes Centro",
    address: "Blvd. José María Chávez No. 1919, Col. San Pedro",
    city: "Aguascalientes",
    country: "México",
    state: "Aguascalientes",
    postalCode: 20230,
    enterpriseId: 3,
  },
  {
    officeName: "City Express Aguascalientes Sur",
    address: "Av. Ayuntamiento 102, Obraje.",
    city: "Aguascalientes",
    country: "México",
    state: "Aguascalientes",
    postalCode: 20280,
    enterpriseId: 3,
  },
  {
    officeName: "Marriott Cancún",
    address: "Blvd. Colosio",
    city: "Cancún",
    country: "México",
    state: "Quintana Roo",
    postalCode: 77500,
    enterpriseId: 2,
  },
  {
    officeName: "Bonvoy Cancún",
    address: "Blvd. Kukulcan.",
    city: "Cancún",
    country: "México",
    state: "Quintana Roo",
    postalCode: 77500,
    enterpriseId: 1,
  },
];

const users = [
  {
    email: "hola@mundo.com",
    password: "$2a$12$mm75a9HEcagLhHJwDcRrBeEIaFhWMkZa1b8CXczhpvTfdLVZNzT4W",
    telefono: "9981111111",
    userName: "Hafid",
    enterprises: [1, 2, 3],
    role: 1,
    typePrice: 1,
    currency: "MXN",
    addresses: [1, 2, 3, 4],
  },
  {
    email: "marriott@marriott.com",
    password: "$2a$12$mm75a9HEcagLhHJwDcRrBeEIaFhWMkZa1b8CXczhpvTfdLVZNzT4W",
    userName: "Marriott",
    telefono: "9981111111",
    role: 2,
    typePrice: 1,
    currency: "MXN",
    enterprises: [1, 2],
    addresses: [3],
  },
  {
    email: "city@express.com",
    password: "$2a$12$mm75a9HEcagLhHJwDcRrBeEIaFhWMkZa1b8CXczhpvTfdLVZNzT4W",
    userName: "City Express",
    telefono: "9981111111",
    role: 2,
    typePrice: 2,
    currency: "MXN",
    enterprises: [1, 3],
    addresses: [2],
  },
  {
    email: "test@test.com",
    password: "$2a$12$mm75a9HEcagLhHJwDcRrBeEIaFhWMkZa1b8CXczhpvTfdLVZNzT4W",
    userName: "Test",
    telefono: "9981111111",
    role: 2,
    typePrice: 3,
    currency: "USD",
    enterprises: [1, 2, 3],
    addresses: [3],
  },
];

const categories = [
  {
    categoryName: "General",
    imageCategory: "/images/logos/gruporegio_isotipo.png",
    parentCategory: 2,
    enterprises: [1],
  },
  {
    categoryName: "Stationary",
    imageCategory: "/images/logos/gruporegio_isotipo.png",
    parentCategory: 2,
    enterprises: [2, 3],
  },
  {
    categoryName: "F&B",
    imageCategory: "/images/logos/gruporegio_isotipo.png",
    parentCategory: 2,
    enterprises: [2],
  },
];

const products = [
  {
    sku: "SDGHHJE",
    nameProduct: "Platinum Elite Breakfast Certificate Regular ES",
    imageProduct:
      "/images/products/platinum_elite_breakfast_certificate_regular_es.png",
    priceLocal: 100.0,
    priceNacional: 120.0,
    priceExt: 6.0,
    descriptionProduct: null,
    stockProduct: 200,
    unitsPackage: 100,
    published: true,
    enterpriseId: 1,
    categories: [1],
  },
  {
    sku: "SDGEHJE",
    nameProduct: "Elite Key Packet BE",
    imageProduct: "/images/products/elite_key_packet_be.png",
    priceLocal: 100.0,
    priceNacional: 125.0,
    priceExt: 7.59,
    descriptionProduct: null,
    stockProduct: 200,
    unitsPackage: 100,
    published: true,
    enterpriseId: 1,
    categories: [1],
  },
  {
    sku: "SDGHHRE",
    nameProduct: "GM Note Card Envelope",
    imageProduct: "/images/products/gm_note_card_envelope.png",
    priceLocal: 110.0,
    priceNacional: 125.0,
    priceExt: 7.0,
    descriptionProduct: null,
    stockProduct: 50,
    unitsPackage: 100,
    published: true,
    enterpriseId: 2,
    categories: [2],
  },
  {
    sku: "SDGHGWE",
    nameProduct: "Folio Envelope",
    imageProduct: "/images/products/folio_envelope.png",
    priceLocal: 150.0,
    priceNacional: 170.0,
    priceExt: 11.99,
    descriptionProduct: "some desc folio envelope",
    stockProduct: 50,
    unitsPackage: 100,
    published: true,
    enterpriseId: 2,
    categories: [2],
  },
  {
    sku: "SASHHJE",
    nameProduct: "Coaster",
    imageProduct: "/images/products/coaster.png",
    priceLocal: 170.0,
    priceNacional: 250.0,
    priceExt: 16.0,
    descriptionProduct: "some desc folio envelope",
    stockProduct: 50,
    unitsPackage: 100,
    published: true,
    enterpriseId: 2,
    categories: [3],
  },
  {
    sku: "SWEHHJE",
    nameProduct: "Box City Express",
    imageProduct: "/images/products/box_city_express.jpg",
    priceLocal: 130.0,
    priceNacional: 145.0,
    priceExt: 9.0,
    descriptionProduct: "some desc box city",
    stockProduct: 50,
    unitsPackage: 100,
    published: true,
    enterpriseId: 3,
    categories: [2],
  },
  {
    sku: "SMGHHJE",
    nameProduct: "Corporate Card",
    imageProduct: "/images/products/card_city_express.jpg",
    priceLocal: 110.0,
    priceNacional: 125.0,
    priceExt: 6.0,
    descriptionProduct: "some desc city",
    stockProduct: 50,
    unitsPackage: 100,
    published: true,
    enterpriseId: 3,
    categories: [2],
  },
  {
    sku: "SKWKHHJE",
    nameProduct: "Corporate Letter",
    imageProduct: "/images/products/paper_city_express.jpg",
    priceLocal: 110.0,
    priceNacional: 125.0,
    priceExt: 6.0,
    descriptionProduct: "some desc city",
    stockProduct: 50,
    unitsPackage: 100,
    published: true,
    enterpriseId: 3,
    categories: [2],
  },
];

module.exports = {
  enterpises,
  addresses,
  users,
  categories,
  products,
};
